version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/martinsirbe/go-teapot-server
    steps:
      - checkout
      - run:
          name: Download project dependencies.
          command: go mod download
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build a docker image.
          command: make teapot
      - run:
          name: Push to the docker registries.
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push martinsirbe/go-teapot-server:$(git rev-parse --short $CIRCLE_SHA1)
            echo "$GITHUB_PKG_REG_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_USERNAME" --password-stdin
            docker push docker.pkg.github.com/martinsirbe/go-teapot-server/go-teapot-server:$(git rev-parse --short $CIRCLE_SHA1)
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
  periodic-build:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
